[project]
name = "english-app-backend"
version = "1.0.0"
description = "English Learning API"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.0.0",
    "email-validator>=2.1.0",
    "psycopg2-binary>=2.9.9",
    "python-dotenv>=1.0.0",
    "langchain>=0.1.0",
    "langchain-openai>=0.0.5",
    "python-multipart>=0.0.24",
    "faster-whisper>=1.2.1",
    "librosa>=0.11.0",
    "huggingface-hub>=1.9.2",
    "sqlalchemy>=2.0.0",
    "alembic>=1.18.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt<5.0.0",
    "python-multipart>=0.0.6",
    "fastapi-jwt-auth>=0.5.0",
    "jupyter>=1.1.1",
    "langchain-deepseek>=1.0.1",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]
[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
